var express = require('express');
var router = express.Router();
module.exports = function() {
  require("./index")(router);
  require("./information")(router);
  require("./safety")(router);
  require("./data")(router);
  require("./pay_setting")(router);
  require("./trading_setting")(router);
  require("./receiving_address")(router);
  require("./remind_setting")(router);
  require("./share_setting")(router);
  require("./collection/commodity")(router);
  require("./collection/product")(router);
  require("./collection/store")(router);
  require("./collection/sold")(router);
  require("./collection/onsale")(router);
  require("./collection/warehouse")(router);
  require("./collection/bought")(router);
  require("./collection/review")(router);
  require("./comment/comment")(router);
  require("./comment/reply")(router);
  require("./goods/publish")(router);
  require("./merchant/register")(router);
  require("./express/setting")(router);
  require("./express/edit")(router);
  require("./express/freight")(router);
  return router;
};
